// Generated by https://quicktype.io

export interface MainStatsModel {
  data: MainData;
  _meta: Meta;
}

export interface Meta {
  version: string;
}

export interface MainData {
  accounts: number | bigint;
  tvl: number | bigint;
  event_count: number | bigint;
  total_events_value: number | bigint;
  message_cost: number | bigint;
}
